Update pipelines.yml

diff --git a/.jfrog-pipelines/pipelines.yml b/.jfrog-pipelines/pipelines.yml
--- a/.jfrog-pipelines/pipelines.yml
+++ b/.jfrog-pipelines/pipelines.yml
@@ -1,51 +1,89 @@
-#template: true   # required for local templates
-valuesFilePath: ./values.yml
-
-resources:
-  - name: npm_repo_jfp_example
-    type: GitRepo
+name: intro_hello_world
+steps:
+  - name: first
+    type: Bash
+    execution:
+      onStart:
+        - >-
+          echo "onStart can be used to do some setup or initialization of your
+          dependencies to prepare for the execution."
+      onExecute:
+        - >-
+          echo "onExecute is the main section where you would issue your
+          build/test commands"
+        - jfrog --version
+      onSuccess:
+        - >-
+          echo "onSuccess executes if the onStart or onExecute sections
+          completed without errors"
+      onFailure:
+        - >-
+          echo "onFailure executes if either onStart or onExecute end in failure
+          or error."
+      onComplete:
+        - echo "onComplete executes after onSuccess or onFailure"
+  - name: variable_selection
+    type: Bash
     configuration:
-      # SCM integration where the repository is located
-      gitProvider: {{ .Values.myRepo.gitProvider }}
-      # Repository path, including org name/repo name
-      path: {{ .Values.myRepo.path }}
-      branches:
-        # Specifies which branches will trigger dependent steps
-        include: master
-
-  - name: npm_buildinfo_jfp_example
-    type: BuildInfo
+      inputSteps:
+        - name: first
+      environmentVariables:
+        forceFail:
+          default: 'false'
+          description: set to 'true' to force the step to fail.
+          values:
+            - 'false'
+            - 'true'
+    execution:
+      onStart:
+        - 'if [ ${forceFail} == "true" ]; then exit 1; fi'
+      onExecute:
+        - echo "This step will succeed"
+      onFailure:
+        - echo "step has failed."
+      onSuccess:
+        - echo "step has succeeded."
+      onComplete:
+        - >-
+          echo "onComplete executes regardless of success or failure. forceFail
+          is ${forceFail}"
+  - name: add_run_variable
+    type: Bash
     configuration:
-      sourceArtifactory: {{ .Values.myRepo.artifactory }}
-      
-  - name: cron_trigger_npm
-    type: CronTrigger
+      inputSteps:
+        - name: first
+    execution:
+      onStart:
+        - echo "This step will save a value to a run variable."
+      onExecute:
+        - >-
+          add_run_variables step_info="runNumber $run_number, step_name
+          $step_name, pipeline_name $pipeline_name"
+  - name: write_to_resource
+    type: Bash
     configuration:
-      interval: '0 3 * * *'       
-
-pipelines:
-  - name: Npm_Quickstart
-    steps:
-      - name: npm_build_step
-        type: NpmBuild
-        configuration:
-          repositoryName: quickstarts-npm-virtual      # required, npm repository name on artifacctory
-          sourceLocation: .      # required, location of package.json file
-          integrations:
-            - name:  {{ .Values.myRepo.artifactory }}  # required
-          inputResources:
-            - name: npm_repo_jfp_example         # required
-            - name: cron_trigger_npm
-
-      - name: npm_publish_step
-        type: NpmPublish
-        configuration:
-          # for payloadType npm:
-          repositoryName: quickstarts-npm-virtual        # required, npm repository name on artifactory
-          autoPublishBuildInfo: true       # optional
-          integrations:
-            - name: {{ .Values.myRepo.artifactory }}      # required
-          inputSteps:
-            - name: npm_build_step                # required
-          outputResources:
-            - name: npm_buildinfo_jfp_example                 # optional
+      inputSteps:
+        - name: add_run_variable
+        - name: variable_selection
+      outputResources:
+        - name: intro_bag
+    execution:
+      onStart:
+        - echo "Printing the run variable 'step_info' from previous step"
+        - 'echo "${step_info}"'
+      onExecute:
+        - echo "Updating resource intro_bag with new key/value pairs"
+        - write_output intro_bag "timestamp=$(date +%s)"
+        - 'write_output intro_bag "releaseVersion=${pipeline_name}.${run_number}"'
+        - 'write_output intro_bag "stepInfo=${step_info}"'
+  - name: read_from_resource
+    type: Bash
+    configuration:
+      inputResources:
+        - name: intro_bag
+    execution:
+      onExecute:
+        - echo "printing resource details"
+        - 'echo "Release Version is -- ${res_intro_bag_releaseVersion}"'
+        - 'echo "Release timestamp is -- ${res_intro_bag_timestamp}"'
+        - 'echo "Step Info is -- ${res_intro_bag_stepInfo}"'
